---
name: on_ZeAuth_event1
pack: ZeAuth
description: Sample rule firing on ZeAuth.event1.
enabled: true
trigger:
    type: ZeAuth.event1
action:
    ref: ZeAuth.greet
    parameters:
        greeting: Yo
